name: Obfuscate JS Code

on:
    push:
        branches: ["master"]

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    obfuscate:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Obfuscate JS Code
          run: |
            cd $GITHUB_WORKSPACE/
            sudo npm install uglify-js -g
            sudo npm install javascript-obfuscator -g
            rm ./otp.min.js
            uglifyjs ./otp.js -c -o ./output.js
            javascript-obfuscator ./output.js -o ./otp.min.js --options-preset high-obfuscation
            rm ./output.js
        - name: Commit files
          run: |
            git config --local user.email "n1993r-actions[bot]@users.noreply.github.com"
            git config --local user.name "n1993r[bot]"
            git commit -a -m "Obfuscate js code"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
